version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - misspell
    - revive
    - unconvert

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
